### ISSUE TITLE
Restore table grid enforcement

### ISSUE THREAD

**Issue by chriscarrollsmith** [chriscarrollsmith/monospace-blog#20]
I think the reason it's failing is because 'th' elements don't have the width-auto class assigned to them. We want to assign this class if either it or width-min aren't already present on the element.

**Comment by chriscarrollsmith** [comment]
# Table Column Character Rounding Problem Summary

## Problem Statement

The user wanted to implement character-width rounding for table columns, similar to how the grid system and table width already use rounding to ensure alignment with the monospace character grid. The goal was to make table column widths round to exact character boundaries (multiples of `1ch`) for perfect visual alignment in the monospace blog theme.

## Context

The existing codebase already had successful character-width rounding implementations:
- Grid system: `calc(round(down, (100% - (1ch * (var(--grid-cells) - 1))) / var(--grid-cells), 1ch))`
- Table width: `calc(round(down, 100%, 1ch))`
- Body max-width: `calc(min(80ch, round(down, 100%, 1ch)))`

## Attempted Solutions

### 1. Initial Manual Width Utilities
**Approach**: Created utility classes for manual column width assignment
```css
.width-10ch { width: calc(round(down, 10ch, 1ch)); }
.width-25 { width: calc(round(down, 25%, 1ch)); }
/* etc. */
```
**Problem**: Required manual application to each column depending on table structure - not automatic like the grid system.

### 2. Automatic Column Detection with round()
**Approach**: Automatic system using `:has()` selectors and CSS custom properties
```css
table {
  --table-cols: 0;
}

table:has(tr:first-child > :last-child:nth-child(3)) { --table-cols: 3; }

table:not(.manual-width) th,
table:not(.manual-width) td {
  width: calc(round(down, 100% / var(--table-cols), 1ch));
}
```
**Problem**: The `round()` function appeared to not be working in the browser - computed styles showed fractional pixel values instead of character-aligned widths.

### 3. Mathematical Rounding Simulation
**Approach**: Attempted to simulate `round()` function behavior with complex calc expressions
```css
width: calc((100% - (100% - calc(100% / var(--table-cols) / 1ch) * 1ch)) / var(--table-cols));
```
**Problem**: The mathematical approach didn't produce the expected rounding behavior.

### 4. Case-by-Case Character-Aligned Rules
**Approach**: Specific rules for common column counts using mathematical rounding tricks
```css
table:not(.manual-width):has(tr:first-child > :last-child:nth-child(3)) th,
table:not(.manual-width):has(tr:first-child > :last-child:nth-child(3)) td {
  width: calc((100% - (100% - calc(100% / 3 / 1ch) * 1ch)) / 3);
}
```
**Problem**: Still produced fractional pixel values (242.585px instead of character-aligned widths).

### 5. Fixed Character Widths
**Approach**: Abandon percentage-based calculations, use fixed character widths
```css
table:not(.manual-width):has(tr:first-child > :last-child:nth-child(3)) th,
table:not(.manual-width):has(tr:first-child > :last-child:nth-child(3)) td {
  width: 26ch;
}
```
**Problem**: User rejected this approach (presumably because it doesn't respect container width).

## Attempt 6 – Turn the table into a CSS grid + JavaScript post-processing

**Approach**
1.  Converted `<table>` into a grid container (`display: grid`) and tried to flatten wrappers with `display: contents` so each cell would become a grid item.
2.  Added a JS helper (`adjustTableColumnWidths()` in `static/grid.js`) that:
    • measures the exact pixel width of `1ch`,
    • counts how many columns are in the first row,
    • calculates a per-column width that is an integer multiple of the character width, and
    • injects an explicit `grid-template-columns` track list so every internal grid line should land on the monospace grid.

**Result** – No visible improvement
• Cells still rendered with `display: table-cell` (UA stylesheet wins); `display: contents` cannot pierce table semantics in current engines, so the grid never took effect.
• Inline `grid-template-columns` therefore had no influence; computed widths stayed fractional (e.g. `225.241 px`).
• Even with explicit JavaScript snapping, the browser continues to use the table layout algorithm, bypassing the grid rules entirely.

**Lesson Learned**
CSS cannot repurpose the table formatting context into a true grid by simply changing `display` values—the internal table algorithm is special-cased. Any grid tricks will be ignored unless the markup is replaced with non-table elements.

## Attempt 7 – JavaScript-driven `<colgroup>` Injection

**Approach**
1.  Set `table-layout: fixed;` on the table to ensure column widths are dictated by a single authority, not cell content.
2.  Modified the `adjustTableColumnWidths()` JS helper to:
    *   Measure the table's total width in pixels (which is already rounded to the nearest character by `calc(round(down, 100%, 1ch))`).
    *   Calculate the total number of characters that fit across the table.
    *   Distribute the characters as evenly as possible among the columns.
    *   Inject a `<colgroup>` element into the table, populated with `<col>` elements, each with its `width` set explicitly in `ch` units (e.g., `<col style="width: 12ch">`).
3.  This script runs on page load and on window resize.

**Result** – A partial success with major regressions.
*   **Success**: The borders of the table cells now land perfectly on the monospace character grid.
*   **Failure 1 (Broken Manual Sizing)**: The script programmatically sets an explicit width for *every* column, overriding any utility classes like `.width-min`. This breaks the ability to have columns of different, intentional sizes.
*   **Failure 2 (Broken Reactivity)**: The table no longer resizes with the viewport. The combination of `table-layout: fixed` and JS-injected `ch` widths on the `<col>` elements appears to prevent the browser's responsive reflow, making the layout static after the initial calculation.

**Lesson Learned**
Using JavaScript to inject `<colgroup>` is the semantically correct way to control table columns, and it can solve the character-grid alignment problem. However, a simple "divide-by-n" script is too naive for a real-world system, as it breaks both responsiveness and manual width overrides. The `table-layout: fixed` property, while necessary for precision, makes the table layout rigid and less adaptive to viewport changes when column widths are set this way.

---

# Final Takeaways (2025-06-29)
1. `round()` still fails whenever the *value* and the *step* use incomparable units (percentage vs `ch`). That is the root cause of the original idea not working.
2. Table layout is hard-wired in browsers; trying to override it with CSS Grid (`display: grid`) plus `display: contents` on rows/sections does not work reliably – cells remain `table-cell`.
3. A JS fallback can only work if the table is turned into a real flex/grid layout or the script rewrites the DOM; merely setting `grid-template-columns` is ignored by the table algorithm.
4. Achieving pixel-perfect, character-aligned column widths while keeping semantic `<table>` markup appears impossible with current CSS capabilities alone.
5. The pragmatic path is to accept tiny sub-pixel deviations or build the table with non-table markup that can be fully controlled by Grid/Flexbox.

## Key Findings

### What Worked
1. **Column Detection**: The `:has()` selector system worked perfectly
   - `--table-cols: 3` was correctly computed
   - Automatic detection of column count was successful

2. **Table Width Rounding**: The overall table width rounding worked fine
   - `calc(round(down, 100%, 1ch))` functioned as expected

### What Didn't Work
1. **CSS round() Function**: Despite being in computed styles, the `round()` function didn't produce rounded results
   - Browser support issue or implementation bug
   - Expressions like `calc(round(down, 100% / var(--table-cols), 1ch))` computed to fractional pixels

2. **Mathematical Rounding Simulation**: Complex calc expressions failed to replicate rounding behavior
   - Order of operations issues
   - CSS calc limitations with nested expressions

## Browser Support Context

- **CSS round() function**: Baseline 2024 (very new feature, since May 2024)
- **CSS :has() selector**: Baseline 2023 (newer feature, since December 2023)
- Both features have good modern browser support but may not work in older browsers or have implementation bugs

## Conclusions

1. **The fundamental approach was sound**: Using `:has()` for automatic column detection and CSS custom properties for dynamic width calculation
2. **The CSS round() function is unreliable**: Either due to browser bugs or incomplete implementation
3. **Mathematical simulation of rounding in CSS is complex**: CSS calc has limitations that make precise rounding difficult
4. **Character-perfect alignment may require compromise**: Perfect character alignment for table columns might need to sacrifice responsive behavior

## Recommendations for Future Attempts

1. **Feature Detection**: Check CSS.supports() for round() function before using
2. **Progressive Enhancement**: Provide fallback styles for browsers without round() support
3. **Alternative Approaches**:
    *   **Smarter JavaScript**: The script could be enhanced to support responsiveness and manual sizing.
        *   **Responsiveness**: Instead of setting widths in `ch`, the script could set them in pixels (`style.width = \`${chars * charWidth}px\`). Since the script re-runs on resize, this would force a pixel-perfect, responsive layout that is recalculated on every change.
        *   **Manual Sizing**: The script could be taught to respect pre-existing styles. It could detect columns with classes like `.width-min` or `width: auto`, let the browser lay those out first, measure the remaining space, and then distribute that remainder among the other columns. This would add significant complexity.
    *   **Pure CSS (Revisited)**: The original idea of using `round()` in CSS is the most elegant. It's worth re-evaluating if there is a different syntax or context where `round()` can be made to work with mixed percentage and `ch` units for table cells.
4. **Simpler Goals**: Accept "close enough" alignment rather than perfect character boundaries

**Comment by chriscarrollsmith** [comment]
o3 suggests this: just add `class="grid-table"` to any table where you want reliable column widths:

```css
/* Grid table implementation for reliable column widths */
table.grid-table {
  display: grid;
  border-collapse: collapse;
  --col: round(
    (100% - (var(--border-thickness) * (var(--table-cols) + 1)))
    / var(--table-cols),
    1ch
  );
}

/* Remove row boxes so cells become grid items */
table.grid-table > thead > tr,
table.grid-table > tbody > tr,
table.grid-table > tfoot > tr {
  display: contents;
}

/* Grid template columns for different column counts */
table.grid-table:has(tr:first-child > :last-child:nth-child(1)) {
  grid-template-columns: 1fr;
}

table.grid-table:has(tr:first-child > :last-child:nth-child(2)) {
  grid-template-columns: var(--col) 1fr;
}

table.grid-table:has(tr:first-child > :last-child:nth-child(3)) {
  grid-template-columns: var(--col) var(--col) 1fr;
}

table.grid-table:has(tr:first-child > :last-child:nth-child(4)) {
  grid-template-columns: var(--col) var(--col) var(--col) 1fr;
}

table.grid-table:has(tr:first-child > :last-child:nth-child(5)) {
  grid-template-columns: var(--col) var(--col) var(--col) var(--col) 1fr;
}

table.grid-table:has(tr:first-child > :last-child:nth-child(6)) {
  grid-template-columns: var(--col) var(--col) var(--col) var(--col) var(--col) 1fr;
}

table.grid-table:has(tr:first-child > :last-child:nth-child(7)) {
  grid-template-columns: var(--col) var(--col) var(--col) var(--col) var(--col) var(--col) 1fr;
}

table.grid-table:has(tr:first-child > :last-child:nth-child(8)) {
  grid-template-columns: var(--col) var(--col) var(--col) var(--col) var(--col) var(--col) var(--col) 1fr;
}

table.grid-table:has(tr:first-child > :last-child:nth-child(9)) {
  grid-template-columns: var(--col) var(--col) var(--col) var(--col) var(--col) var(--col) var(--col) var(--col) 1fr;
}
```
